### ISSUE TITLE
here have these like three things that you need to fix

### ISSUE THREAD

**Issue by robingall2910** [Maxie01/we-made-a-theme#13]
this
![meme](http://this.dragonfire.me/website/sucks/b6dvtvx.png)
and this
![meme](http://this.dragonfire.me/website/sucks/etjgi63.png)
im not sure about the second one, that might just be a discord bug and not a theme bug

**Comment by SquirrelsMcGee** [comment]
@Maxie01 papa bless

**Comment by Pierce01** [comment]
WEW its been a while. I'll look into it :)

**Comment by Pierce01** [comment]
OK AYYYYYYY


The 1st is a feature™️

and the 2nd is fixed when they changed the layout.
