### ISSUE TITLE
Local images

### ISSUE THREAD

**Issue by Razzile** [Maxie01/we-made-a-theme#3]
this theme is great but why can I not load local images

0/10

**Comment by jithatsonei** [comment]
+1

**Comment by SquirrelsMcGee** [comment]
Coming Soon™

**Comment by SquirrelsMcGee** [comment]
and by soon i mean in like, 10 minutes

**Comment by SquirrelsMcGee** [comment]
Fixed in most recent commit as of today

**Comment by jithatsonei** [comment]
you can use Fixes #$issuenumber to automatically close an issue

or are you just that shit a git you GUI using faggot

**Comment by SquirrelsMcGee** [comment]
Amazing comment, doesn't github take harsh language seriously?

**Comment by jithatsonei** [comment]
Don't you take being a faggot easily :^)

**Comment by Pierce01** [comment]
Smh better discord community is aids

Also reopened, for flame wars

**Comment by SquirrelsMcGee** [comment]
:eyes: 
lmao
alucard is salty because he went back to school

**Comment by jithatsonei** [comment]
;_;
also I'm not from betterdiscord
I'm the dude who accidentally deleted the site

**Comment by Pierce01** [comment]
@alucard0134 U WAT

**Comment by Pierce01** [comment]
No more flame wars, i cri

**Comment by Razzile** [comment]
:c
