### ISSUE TITLE
Emotes and message options buttons are not accessible.

### ISSUE THREAD

**Issue by 1amnick** [Maxie01/we-made-a-theme#8]
When trying to click on the reaction button or message the buttons disappear when getting near them.
https://gfycat.com/SlimyBleakAmericanbadger

**Comment by SquirrelsMcGee** [comment]
will sort a fix soon

**Comment by Sheepverse** [comment]
When will this get fixed?
Is there a workaround like hiding the user pannel with ctrl+u? Well, this don't fixes the problem.

**Comment by Pierce01** [comment]
Working on it now

**Comment by Pierce01** [comment]
Fixed in latest update. its not pushed to dev yet. Closing issue
